version: 0.2

phases:
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      - mv target/my-web-app.war my-web-app.war
artifacts:
  files:
    - my-web-app.war
    - .ebextensions/**/*